name: Playwright Tests
on:
  workflow_call:
    inputs:
      playwright_version:
        description: Installed playwright version
        required: false
        default: '1.51.1'
        type: string

jobs:
  end-to-end:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v${{ inputs.playwright_version }}-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install required node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ inputs.playwright_version }}

      - name: Install Playwright
        run: pnpm dlx playwright@${{ inputs.playwright_version }} install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      # While most of the test suite is self-contained, the tests for the demo
      # servers require a prod build of @atj/server.
      - name: Build
        run: pnpm build

      - name: Run end-to-end tests
        shell: bash
        run: pnpm --filter=@gsa-tts/forms-e2e test:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30