name: Playwright Tests
on:
  workflow_call:
    inputs:
      playwright_version:
        description: Installed playwright version
        required: false
        default: '1.51.1'
        type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v${{ inputs.playwright_version }}-noble

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: true

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ inputs.playwright_version }}

      - name: Install Playwright
        run: pnpm dlx playwright@${{ inputs.playwright_version }} install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run end-to-end tests
        shell: bash
        run: pnpm --filter=@gsa-tts/forms-e2e test:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30