name: Apply Terraform CDK configuration

on:
  workflow_call:
    inputs:
      deploy-env:
        type: string
        required: true
      terraform_version:
        description: Terraform version
        required: false
        default: "1.10.4"
        type: string

env:
  DEPLOY_ENV: ${{ inputs.deploy-env }}

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install required node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - uses: actions/cache@v3
        name: Check Cache for Terraform CLI
        id: terraform-cache
        with:
          path: /usr/local/bin/terraform
          key: terraform-${{ inputs.terraform_version }}

      - name: Install Terraform CLI
        if: steps.terraform-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/${{ inputs.terraform_version }}/terraform_${{ inputs.terraform_version }}_linux_amd64.zip
          unzip terraform_${{ inputs.terraform_version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Verify Terraform Installation
        run: terraform --version

      - name: Initialize Terraform CDK configuration
        shell: bash
        working-directory: infra/cdktf
        run: |
          pnpm cdktf get
          pnpm build:tsc

      - name: Install CloudFoundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | sudo tar -zx --directory=/usr/local/bin
          cf --version

      - name: Apply Terraform CDK configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
        working-directory: infra/cdktf
        run: |
          cf api https://api.fr.cloud.gov
          DEPLOY_ENV=${DEPLOY_ENV} pnpm cdktf deploy --auto-approve
