name: 'Deploy'

on:
  push:
    branches:
      - main
      - demo
      - aws-cdk-starter
  workflow_dispatch:

jobs:
  build-image-doj:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-doj
      tag-name: ${{ github.ref_name }}
      deploy-key: "${{ github.ref_name == 'main' && 'dev' || 'demo' }}"

  deploy:
    needs: [build-image-doj]
    uses: ./.github/workflows/_terraform-apply.yml
    secrets: inherit
    with:
      #deploy-env: ${{ github.ref_name }}
      deploy-env: main
